config/routes.rb
Rails.application.routes.draw do
  root :to => 'questions#index'

  resources :questions do
    resources :answers
  end

  resources :users

  get "/log-in" => "sessions#new", as: :log_in
  post "/log-in" => "sessions#create"
  get "/log-out" => "sessions#destroy", as: :log_out
end

app/models/answer.rb
class Answer < ActiveRecord::Base

  validates :text, :presence => true

  belongs_to :user
  belongs_to :question

  has_many :comments, dependent: :destroy

  scope :daily, -> { where(created_at: Time.current.all_day) }
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  validates :text, :presence => true

  belongs_to :user
  belongs_to :answer

end

app/models/question.rb
class Question < ActiveRecord::Base

  validates :title, :presence => true
  validates :text, :presence => true

  belongs_to :user
  has_many :answers, dependent: :destroy

  has_many :votes, dependent: :destroy
  has_many :upvoters, through: :votes, source: :user

  scope :daily, -> { where(created_at: Time.current.all_day) }

end

app/models/user.rb
require 'bcrypt'
class User < ActiveRecord::Base
  attr_accessor :password
  validates_confirmation_of :password
  before_save :encrypt_password
  after_create :send_welcome_message

  validates :email, :presence => true, :uniqueness => true

  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :votes, dependent: :destroy
  has_many :upvoted_questions, through: :votes, source: :question

  scope :admin, -> { where(admin: true) }

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

  def self.authenticate(email, password)
    user = User.where(email: email).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def send_welcome_message
    WelcomeMessage.welcome_email(self).deliver_now
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  validates_uniqueness_of :question_id, scope: :user_id
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_filter :current_user
  
  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new(answer_params)
    @answer.user_id = @current_user.id
    if @answer.save
      flash[:notice] = 'Your answer has been saved.'
      redirect_to question_path(@question)
    else
      flash[:alert] = "Your answer has not been saved!"
      redirect_to question_path(@question)
    end
  end

  private
  def answer_params
    params.require(:answer).permit(:text)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :current_user

  def index
    @questions = Question.all
    @question = Question.new
    @answers = Answer.all
  end

  def create
    @question = @current_user.questions.new(question_params)
    if @question.save
      flash[:notice] = 'Your question has been saved.'
      redirect_to '/'
    else
      flash[:alert] = 'There was a problem saving your question.'
      redirect_to '/'
    end
  end

  def show
    @question = Question.find(params[:id])
    @answers= @question.answers
    @answer = Answer.new
  end

  private
  def question_params
    params.require(:question).permit(:title, :text)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      flash[:notice] = "You've been logged in."
      session[:user_id] = @user.id
      redirect_to "/"
    else
      flash[:alert] = "There was a problem logging you in."
      redirect_to log_in_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've been logged out successfully"
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :current_user
  helper_method :sort_column, :sort_direction

  def index
    @users = User.order(sort_column + ' ' + sort_direction)
    @question = Question.new
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome to the site!"
      redirect_to "/"
    else
      flash[:alert] = "There was a problem creating your account. Please try again."
      redirect_to :back
    end
  end

  def show
    @user = User.find(params[:id])
    @question = Question.new
    @questions = @user.questions
  end

  def update
    @user = User.find(params[:id])
    if params[:admin]
      if @user.update(admin: true)
        redirect_to @user
      else
        flash[:alert] = "There was a problem making this user an admin."
        redirect_to @user
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @questions = @user.questions
    @questions.each do |question|
      question.destroy
    end
    @user.destroy
    flash[:alert] = "The user account has been deleted."
    redirect_to  users_path
  end


  private
  def sort_direction
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
  end

  def sort_column
    User.column_names.include?(params[:sort]) ? params[:sort] : "username"
  end

  def user_params
    params.require(:user).permit(:email, :password, :username, :password_confirmation, :admin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = (column == sort_column) ? "current #{sort_direction}" : nil
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stackicodus</title>
  <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to image_tag("logo.png"), questions_path, :class => 'navbar-brand' %>
      </div>
      <div>
        <ul class="nav navbar-nav">
          <% if @current_user %>
            <li>
              <%= link_to @current_user.username.titleize, user_path(@current_user) %>
            </li>
            <% if @current_user.admin %>
              <li>
                <%= link_to 'All Users', users_path %>
              </li>
            <% end %>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if @current_user %>
            <li>
              <a href="#" data-toggle="modal" id="askQuestion" data-target="#myModal">Ask a Question</a>
            </li>
            <li>
              <%= link_to '<span class="glyphicon glyphicon-log-out"></span> Log Out'.html_safe, log_out_path %>
            </li>
          <% else %>
            <li>
              <%= link_to '<span class="glyphicon glyphicon-log-in"></span> Log In'.html_safe, log_in_path %>
            </li>
            <li>
              <%= link_to '<span class="glyphicon glyphicon-user"></span> Sign Up'.html_safe, new_user_path %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>


  <% if @current_user %>
  <div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Ask a Question</h4>
        </div>
        <div class="modal-body">
          <div class="add_image_form">
            <%= form_for @question do |f| %>
            <div class="form-group">
              <%= f.label :title %>
              <%= f.text_field(:title, {:class => 'form-control', :required => 'true'}) %>
            </div>
            <div class="form-group">
              <%= f.label :text %>
              <%= f.text_field(:text, {:class => 'form-control', :required => 'true'}) %>
            </div>
            <hr>
            <button type="submit" class="btn btn-default">Ask</button>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
  <div class="container">
    <% if flash[:notice] -%>
      <div class = "alert alert-success"><%= flash[:notice] %></div>
    <% end %>
    <% if flash[:alert] -%>
      <div class = "alert alert-danger"><%= flash[:alert] %></div>
    <% end %>
  </div>

  <div class="container">
    <%= yield %>
  </div>

  <div class="footer">
  </div>
</body>
</html>

app/views/questions/_question.html.erb
<tr onclick="location.href='<%= question_path(question) %>'">
  <td><%= question.title %></td>
  <td><%= question.text %></td>
  <td>asked <%= time_ago_in_words question.created_at %> ago by <%= question.user.username %></td>
  <td><span class="badge"><%= question.answers.count %></span></td>
</tr>

app/views/questions/index.html.erb
<div class="container">
  <h3>Top Questions</h3>
  <table class="table table-hover table-responsive">
    <tbody>
      <% @questions.each do |question| %>
        <%= render 'question', :question => question %>
      <% end %>
    </tbody>
  </table>
</div>

<% if @questions.count == 0 %>
  <p> There are currently no questions. It appears everyone is a genius. Congratulations!</p>
<% end %>


<% if @current_user && @current_user.admin %>
  <p>Total Questions Today: <%= @questions.daily.count %></p>
  <p>Total Answers Today: <%= @answers.daily.count %></p>
<% end %>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>

<h3><%= @question.text %><br><small>asked <%= time_ago_in_words @question.created_at %> ago by <%= link_to @question.user.username, @question.user %></small></h3>

<hr>


<% @answers.each do |answer| %>
  <h4><%= answer.text %><br><small>answered <%= time_ago_in_words answer.created_at %> ago by <%= link_to answer.user.username, answer.user %></small>
<% end %>




<% if @current_user %>
<hr>
<%= form_for [@question, @answer] do |f| %>
<h2>Submit your answer: </h2>
<div class="form-group">
  <%= f.label :text %>
  <%= f.text_field(:text, {:class => 'form-control', :required => 'true'}) %>
</div>

<button type="submit" class="btn btn-default">Answer</button>
<% end %>

<% end %>

app/views/users/_user.html.erb
<tr>
  <td><%= user.username %></td>
  <td><%= user.email %></td>
  <td><%= user.created_at.strftime("%b %d") %></td>
  <td><%= user.admin%></td>
</tr>

app/views/users/index.html.erb
<h1>All Users</h1>

total users: <%= @users.count %>
total admin: <%= @users.admin.count %>

<table class="table table-hover table-responsive">
  <thead>
    <tr>
      <th><%= sortable "username" %></th>
      <th><%= sortable "email" %></th>
      <th><%= sortable "created_at", "Member Since" %></th>
      <th><%= sortable "admin" %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr onclick="location.href='<%= user_path(user) %>'">
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.created_at.strftime("%b %d") %></td>
        <td><%= user.admin%></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%=form_for @user do |f| %>
  <%=f.label :username %>
  <%=f.text_field :username %>
  <%=f.label :email %>
  <%=f.text_field :email %>
  <%=f.label :password %>
  <%=f.password_field :password %>
  <%=f.label :password_confirmation %>
  <%=f.password_field :password_confirmation %>
  <%=f.submit "Sign Up" %>
  <%end%>

app/views/users/show.html.erb
<div class="row">
  <div class="col-xs-3">
    <img src="<%= @user.avatar %>" id="user-avatar">
  </div>
  <div class="col-xs-9">
    <h1><%= @user.username %></h1>
    <h5>Is user an administrator? <%= @user.admin %></h5>
    <br>
    <% if current_user && current_user.admin %>
     <%= link_to "Delete User", user_path(@user), :data => {:confirm => "Are you sure?", :method => "delete"} %>
     <br>
     <%= link_to "Make User Admin", user_path(@user, :admin => true), :data => {:method => "patch"} %>
    <% end %>

  </div>
</div>
<h3>Questions Asked</h3>
<br>
<% @user.questions.each  do |question| %>
  <%= question.title %> <br>
  <%= question.text %>
<% end %>

app/views/welcome_message/welcome_email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h1>Welcome to example.com, <%= @user.username %></h1>
    <p>
      You have successfully signed up to example.com,
      your username is: <%= @user.username %>.<br>
    </p>
    <p>
      To login to the site, just follow this link: <%= @url %>.
    </p>
    <p>Thanks for joining and have a great day!</p>
  </body>
</html>

app/views/welcome_message/welcome_email.text.erb
Welcome to example.com, <%= @user.username %>
===============================================

You have successfully signed up to example.com,
your username is: <%= @user.username %>.

To login to the site, just follow this link: <%= @url %>.

Thanks for joining and have a great day!